### ISSUE TITLE
xml regex validator failing

### ISSUE THREAD

**Issue by rienafairefr** [orgoro/coverage#156]
If the xml report has the keys in a different order than in the regex, e.g. 
`<?xml version="1.0" ?>
<coverage branch-rate="0" branches-covered="0" branches-valid="0" complexity="0" line-rate="0.789" lines-covered="344" lines-valid="436" timestamp="1662319474790" version="6.4.4">`

the regex in your action code is `.*<coverage.*lines-valid="(?<total>[\\d\\.]+)".*lines-covered="(?<covered>[\\d\\.]+)".*line-rate="(?<ratio>[\\d\\.]+)"`
which doesnt validate, the xml attributes are just in a different order than expected.

**Comment by orgoro** [comment]
Hey @rienafairefr  thank you for your issue!

How do you make the coverage report? which package & which version

If you use `pytest-cov` can you update to pytest-cov==3.0.0 and retry please?

Thanks

**Comment by rienafairefr** [comment]
coverage.py version 6.4.4, running pytest under it, without pytest-cov. In the end I'm using another action (irongut/CodeCoverageSummary)

**Comment by orgoro** [comment]
Should work now! @rienafairefr you. Can you can retry to run this action
