### ISSUE TITLE
UnhandledPromiseRejectionWarning: HttpError: Resource not accessible by integration

### ISSUE THREAD

**Issue by ct2034** [orgoro/coverage#237]
The action is not doing what it should for me.
See this job for exmaple https://github.com/boschresearch/ros_license_linter/actions/runs/4165753067/jobs/7209189364

```
(node:2157) UnhandledPromiseRejectionWarning: HttpError: Resource not accessible by integration
    at /home/runner/work/_actions/orgoro/coverage/v3/webpack:/typescript-action/node_modules/@octokit/request/dist-node/index.js:86:1
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:2157) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:2157) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by Tientjie-san** [comment]
> The action is not doing what it should for me. See this job for exmaple https://github.com/boschresearch/ros_license_linter/actions/runs/4165753067/jobs/7209189364
> 
> ```
> (node:2157) UnhandledPromiseRejectionWarning: HttpError: Resource not accessible by integration
>     at /home/runner/work/_actions/orgoro/coverage/v3/webpack:/typescript-action/node_modules/@octokit/request/dist-node/index.js:86:1
>     at processTicksAndRejections (internal/process/task_queues.js:97:5)
> (node:2157) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
> (node:2157) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
> ```

Hey im having the same problem did you find a solution?

**Comment by FledgeXu** [comment]
@Tientjie-san @ct2034 Did you setting the `permissions` in Github action? if you did, add the `pull-requests: write` to the action.

**Comment by orgoro** [comment]
@ct2034 did you check what @FledgeXu suggessted?
