### ISSUE TITLE
Status dot colour configuration

### ISSUE THREAD

**Issue by tpgillam** [orgoro/coverage#244]
Currently the status dots in the summary are red & green for failure & success, respectively.

It would be nice to allow the colour to be configured to some degree. This would be especially helpful for those users who cannot easily distinguish red & green.

I'm not sure if it is possible to automatically mirror [GitHub's theme](https://github.blog/changelog/2021-09-29-colorblind-themes-beta/), and e.g. use the same colours that would be used in the UI for adding and deleting code? That would be quite neat.

**Comment by orgoro** [comment]
v3.1 includes this as a config
