### ISSUE TITLE
Escape file names in coverage table

### ISSUE THREAD

**Issue by augustozanellato** [orgoro/coverage#247]
Underscores are not escaped in filenames so instead of \_\_init\_\_.py file names are rendered as __init__.py.
My proposed fix would be replacing `coverFile.file` [here](https://github.com/orgoro/coverage/blob/6101373245c4702eedfa0ba6c56d4586c0d29169/src/format.ts#L26) with `coverFile.file.replaceAll("_", "\\_")`.
A proper solution would be to find some way to escape markdown, but this should cover the majority of use cases.

**Comment by orgoro** [comment]
v3.1

**Comment by augustozanellato** [comment]
Thanks!

**Comment by Sinkler** [comment]
I use v3.2 and there is still an issue

<img width="937" alt="Image" src="https://github.com/user-attachments/assets/122f5d73-f06f-404e-84e0-c67d907bb192" />
