### ISSUE TITLE
Not displaying modified/new file coverage, only repo-wide

### ISSUE THREAD

**Issue by Adrian-at-CrimsonAzure** [orgoro/coverage#248]
Title says it all, we're only getting the repo-wide total:
<img width="346" alt="image" src="https://user-images.githubusercontent.com/96086389/236859972-22408f80-3d90-45a9-8dbe-fae1c06b881e.png">
This PR adds two new files and their tests:
<img width="228" alt="image" src="https://user-images.githubusercontent.com/96086389/236860281-ad51a559-1ea0-4bbc-acb4-fa7317dbb200.png">

I'd be happy to provide sanitized logs or configs if needed.

**Comment by petrovicboban** [comment]
I think this is happening because tests are done on package which is installed via pip, so coverage report has something like:

**Comment by orgoro** [comment]
how are you running your coverage? can you include an example output?

**Comment by dragonpaw** [comment]
I'm having the same issue, though in my case I think it's because I run my tests within a container. In the output from the action it shows:
```
git new files: [] modified files: ["bin/test"]
source: /app/name-of-app
```

Which I think means that it'll only consider things that have a prefix of '/app/name-of-app' as their filename in git, which nothing will have as that's the path within the container. (With 'name-of-app' being the top level directory I'd want reported on as that's where all the python files are based.

I think to cover all the cases, maybe add some more variables we can set on the action, such as allowing us to specify a prefix to remove from the reported paths to get a match to the paths in git?

**Comment by petrovicboban** [comment]
gh action output in my case is:
```
git new files: [] modified files: [".github/workflows/python.yaml",".gitignore","Python/pyproject.toml","Python/random_forestry/forestry.py","Python/tests/test_constructor.py","Python/tests/test_forestry.py","Python/tests/test_forests_equality.py"]
source:
```
and filepaths in `coverage.xml` are like in comment above:
```
  ---------- coverage: platform linux, python 3.8.16-final-0 -----------
  Name                                                                                                   Stmts   Miss  Cover   Missing
  ------------------------------------------------------------------------------------------------------------------------------------
  /tmp/tmp.PCzKULX5yI/venv/lib/python3.8/site-packages/random_forestry/__init__.py                           2      0   100%
  /tmp/tmp.PCzKULX5yI/venv/lib/python3.8/site-packages/random_forestry/forestry.py                         336     71    79%   22, 323-325, 335-337, 340-344, 347-351, 354-365, 370, 384, 587, 598, 616, 632, 634, 636, 647, 669, 687, 689, 691, 702, 725, 732-767, 921-924, 977-994, 1006-1019, 1067, 1204-1206, 1256-1259, 1272-1273
  /tmp/tmp.PCzKULX5yI/venv/lib/python3.8/site-packages/random_forestry/preprocessing.py                    105     29    72%   14-22, 38, 48-66, 83, 88, 141, 153, 203, 220-227, 249
  /tmp/tmp.PCzKULX5yI/venv/lib/python3.8/site-packages/random_forestry/processed_dta.py                     25      0   100%
  /tmp/tmp.PCzKULX5yI/venv/lib/python3.8/site-packages/random_forestry/test.py                              30     30     0%   1-50
  /tmp/tmp.PCzKULX5yI/venv/lib/python3.8/site-packages/random_forestry/validators/__init__.py                8      0   100%
  /tmp/tmp.PCzKULX5yI/venv/lib/python3.8/site-packages/random_forestry/validators/base_validator.py         11      1    91%   15
  /tmp/tmp.PCzKULX5yI/venv/lib/python3.8/site-packages/random_forestry/validators/fit_validator.py         222     29    87%   46, 57, 82, 85, 88, 91, 101, 104, 107, 110, 118, 134, 137, 144, 156, 159, 164, 171, 214, 222, 237, 256, 273, 281, 284, 287, 301, 304, 310
  /tmp/tmp.PCzKULX5yI/venv/lib/python3.8/site-packages/random_forestry/validators/predict_validator.py      75      8    89%   21, 36, 55, 69, 95-98
  ------------------------------------------------------------------------------------------------------------------------------------
  TOTAL   
```


so what I did in `src/coverage.ts` was to remove prefix `Python/` from files reported by git, and then do regex on filepaths reported by `coverage`: 
```
const regex = new RegExp(`.*filename=".*/${fileName}".*line-rate="(?<cover>[0-9]+[.]*[0-9]*)".*`)
```
Note `.*/` in front of `${fileName}`

**Comment by dragonpaw** [comment]
For me the coverage report looks like:
```console
Name                                                                                                  Stmts   Miss  Cover
-------------------------------------------------------------------------------------------------------------------------
name-of-app/__init__.py                                                                                     3      0   100%
...
```

**Comment by petrovicboban** [comment]
@dragonpaw can you try with altering `relative_files` in `coverage` config?
https://coverage.readthedocs.io/en/6.2/config.html#run

**Comment by dragonpaw** [comment]
> @dragonpaw can you try with altering `relative_files` in `coverage` config? https://coverage.readthedocs.io/en/6.2/config.html#run

![image](https://github.com/orgoro/coverage/assets/74992/77ac6f19-a41f-4267-ae2e-09f35e39faa4)

Setting `relative=true` (in pyproject.toml in my case) did indeed fix it so that it now shows the per-file coverage stats.

**Comment by llGines** [comment]
Hi there,

I'm having the same problem. Tried the @dragonpaw solutions (and many others) but no good news for anybody.
Here's my repo:
https://github.com/llGines/checkCalcCoverage

Is a quite simple project, just for testing yours.
Many thanks.

**Comment by llGines** [comment]
> Hi there,
> 
> I'm having the same problem. Tried the @dragonpaw solutions (and many others) but no good news for anybody. Here's my repo: https://github.com/llGines/checkCalcCoverage
> 
> Is a quite simple project, just for testing yours. Many thanks.

what worked for us:
    Using the environment variable {Python_ROOT_DIR?}  provided by  actions/setup-python@v4 
    and setting source= ${Python_ROOT_DIR?}/**/site-packages/ :
