### ISSUE TITLE
Consider re-assigning major version tag on new releases

### ISSUE THREAD

**Issue by mikix** [orgoro/coverage#297]
Most actions (for just one example: https://github.com/actions/checkout) offer a "bare" v3 or v4 tag that updates to point at the latest 3.x or 4.x release. This helps avoid action churn for people pointing at them.

orgoro/coverage doesn't yet do that, but it'd be helpful if it did.

Since that may arguably be surprising for existing folks pointing at the v3 tag, maybe it's wise to start doing this on a new v4 / v4.0 line of releases. (Though there's another argument that they would have been expecting this, but :shrug:)

**Comment by orgoro** [comment]
agreed!
will do
